logging:
  file:
    path: logs
  level:
    com.mih.webauthn: DEBUG
    io.github.webauthn: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.h2: DEBUG
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
     FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
webauthn:
  relying-party-id: localhost
  relying-party-name: Example Application
  relying-party-icon: http://localhost:8100/assets/logo.png
  relying-party-origins: http://localhost:8080,http://localhost:4200,http://192.168.0.111:8080
management:
  metrics:
    enable:
      jvm: true
  endpoint:
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: logfile,health,threaddump,mappingss
