logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.h2: DEBUG
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
     FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
webauthn:
  relying-party-id: localhost
  relying-party-name: Example Application
  relying-party-icon: http://localhost:8100/assets/logo.png
  relying-party-origins: http://localhost:4200
