#keytool -genkeypair -alias localhost -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore localhost.p12 -validity 3650
#keytool -genkeypair -alias localhost -keyalg RSA -keysize 2048 -keystore localhost.jks -validity 3650
#keytool -importkeystore -srckeystore localhost.jks -destkeystore localhost.p12 -deststoretype pkcs12
#openssl pkcs12 -in localhost.p12 -clcerts -nokeys -out demo.crt
#openssl pkcs12 -in localhost.p12 -nocerts -out demo.key
#keytool -exportcert -keystore localhost.jks -alias localhost -file demo.crt

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certs/localhost.p12
    key-store-password: password
    key-alias: localhost
    enabled: true
  port: 8443
